spring:
  application:
    name: music-application
    
  r2dbc:
    url: r2dbc:h2:file:///./data/testdb;
    username: sa
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath:query/ddl-h2.sql

  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 5

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs
